### ISSUE TITLE
GeckoDriver Exception

### ISSUE THREAD

**Issue by RoxxoPentesting** [ExpertAnonymous/PhoneInfoga#2]
![Screenshot_20200929-221153_Termux](https://user-images.githubusercontent.com/71342574/94639004-cfd81580-02a0-11eb-9360-805fdc2fefc7.png)
[*] Running OVH scan...
[*] Running OSINT footprint reconnaissance...
[i] Generating scan URL on 411.com...
[+] Scan URL: https://www.411.com/phone/1-914-226-4505
Would you like to use an additional format for this number ? (y/N) n
[i] ---- Web pages footprints ----
[i] Searching for footprints on web pages... (limit=10)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "phoneinfoga.py", line 95, in <module>
    main()
  File "phoneinfoga.py", line 71, in main
    scanNumber(args.number)
  File "phoneinfoga.py", line 38, in scanNumber
    osintScan(number)
  File "/data/data/com.termux/files/home/PhoneInfoga/scanners/footprints.py", line 186, in osintScan
    for result in search(req, stop=10):
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 49, in search
    browser = getFirefoxBrowser()
  File "/data/data/com.termux/files/home/PhoneInfoga/lib/googlesearch.py", line 32, in getFirefoxBrowser
    return webdriver.Firefox()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by HarleyWildman** [comment]
Has anyone found a solution to this?
